# Generated by Django 3.1.3 on 2020-11-15 16:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20201114_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arnuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
